### ISSUE TITLE
Border expansion mask "in X turns" button not shown beyond 3rd ring from city

### ISSUE THREAD

**Issue by zxcvforz** [CQUI-Org/cqui#153]
This is a cosmetic problem that has little to no influence to gameplay.

![289070_20161130114832_1c](https://cloud.githubusercontent.com/assets/6653593/20739145/2b72c7c6-b6f3-11e6-880e-779ce4cc17c4.jpg)

When the next border expansion is beyond the city's 3rd ring, the "in X turns" button will not be shown. If I switch to another city that has the button and click it to hide the mask, then come back to this city in the image above, then the masking also disappears and there's no way to see where the next border expansion will be.

I can imagine that I'd want to know if my border is going to expand to cover an offshore oil or some other late game strategic resource that's sitting on the 4th ring of my city, but otherwise it doesn't affect the gameplay at all.

Save for the image above attached:
[BorderExpansionMaskBeyond3rdRing.zip](https://github.com/chaorace/cqui/files/620914/BorderExpansionMaskBeyond3rdRing.zip)

**Comment by chaorace** [comment]
This is a little tough since the layer the next plot mod uses only draws 3 tiles out from the city, whereas the filter firaxis added works everywhere. I think the best solution here would be expanding the radius of that city overlay part to 6 tiles out, but I'm not sure how simple of a proposition that would be
