### ISSUE TITLE
Right clicking on minimap moves selected unit

### ISSUE THREAD

**Issue by mp0011** [CQUI-Org/cqui#203]
If i have selected unit, and right click on minimap to zoom it in or out, unit gets order to move to hex directly beyond minimap (as if there were no minimap, and I click hex directly).

**Comment by Frozen-In-Ice** [comment]
@chaorace I was thinking about this one and wondering, if you made the minimap consume the mouse, and then made the minimap toggle on right mouse button's release (instead of on press as it currently is), then the unit movement code shouldn't find a tile to move to when it checks when the right mouse button is released, right?

**Comment by papaguss** [comment]
Correct ! the um code doesn't locate the tile.but right clicking does nothing(minimap slider works ok)

**Comment by chaorace** [comment]
The toggle size functionality was removed with the introduction of the minimap size slider, since it's a much  more elegant solution to the design problem
