### ISSUE TITLE
Long resource list hides turn indicator

### ISSUE THREAD

**Issue by vttale** [CQUI-Org/cqui#240]
In the top status bar, if you have a lot of resources then the turn indicator / year will completely disappear.  It shows resources -> plus-in-circle extended resource button -> View Reports button -> Clock -> Civpedia icon -> Hamburger menu.

**Comment by vttale** [comment]
Looks like it might still be rendered but under the View Reports button.

**Comment by chaorace** [comment]
Probably has something to do with how the view reports button is inserted there. I'll look into rearranging the stack to fix this

**Comment by JHCD** [comment]
If the resource list is long enough there will be nothing right of the _View Report_-button.
But I have seen, that there will be a (+) Icon left to the _View Report_-button where all the other resources are shown in a pop-up.
The solution have to be, that the _View Report_-button have to stop in front of the turn indicator. 
Moving the remaining icons into the (+) is existing.
In this content: could you change the order? Strategic resources should shown first so that the other resources will go in the (+) and not the strategic onces.

**Comment by chaorace** [comment]
Reports button has been moved, issue resolved
