### ISSUE TITLE
Diplomacy Deals: Mutual resource highlighting disclose hidden informations

### ISSUE THREAD

**Issue by JHCD** [CQUI-Org/cqui#406]
I have the problem, that ressources are colored which the other Civ doesn't have itself.
There are no deals between them and me.
First I suspected that the other Civs have deals among each other and this is an hidden information.

Update: More infos to the pictures:

Spain:
![error_spain](https://cloud.githubusercontent.com/assets/12496340/24071834/a30bf8f6-0bdb-11e7-940e-b1be6e4aba8a.jpg)
Isn't a Suzerain and have no coloring matter in his area...

Greece:
![error_greek](https://cloud.githubusercontent.com/assets/12496340/24071800/22fcce10-0bdb-11e7-8c52-300b5dac298f.jpg)
Suzerain, with the following bonus ressources:
1x cotton, 1x salpeter, 1x crabs, 1x fish, 1x  coloring matter
Cotton is highlighted
But why aluminium, horse and salpeter arn't highlighted?

Japan:
![error_japan](https://cloud.githubusercontent.com/assets/12496340/24071836/ad110a08-0bdb-11e7-9f1e-d6751b11bc6a.jpg)
Suzerain, with the following bonus ressources:
1x cotton, 1x salpeter, 3x fish, 1x copper, 1x tabac
Cotton is highlighted

England:
Horse isn't highlighted

**Comment by chaorace** [comment]
Very interesting... could you provide an affected save file?

**Comment by ricanuck** [comment]
@JHCD : strange, it has been very consistent so far in my tests/games, and I don't see anything that could explain this behavior in the code. Some options:
1. Provide a save so we can try it and see if it happens also on our end.
2. Try the new addition (IDS mod) once Chris commits it. It should show exactly what is happening.
3. Are you sure the resources are not coming from City States that the civs are Suzerains of?

**Comment by JHCD** [comment]
Oh, I have forgottem the Suzerains... There is cotton and coloring matter available for Greek for second and third screen...
The first one isn't a Suzerains, so he have to have a deal with somebody.

**Comment by JHCD** [comment]
I have updated the starting post...
@chaorace I sent you a savegame per eMail

**Comment by chaorace** [comment]
Here's [a link](https://team-cqui.slack.com/files/chaorace/F4LBQ3X6E/harald_hardr__de_3.civ6save) in case anyone else wants to check it out as well

**Comment by ricanuck** [comment]
@JHCD : the code is in place only to check for duplicates regarding luxuries. I am not sure if it makes sense to also check for strats. In any case, we should first test/try the customized IDS mod and see if that fits our goals better, or if we need to modify it further.

**Comment by ricanuck** [comment]
Tested the save file with both the present diplodealview and the new IDS mod:
OK, so Spain was the first claim... Spain has Dyes coming from "another civ" (I modified the code so that it only shows from where it comes if it is the player)
Pericles has Cotton and Dyes as suzerain of Kandy and Yerevan
Japan has cotton as suzerain of Mohenjo something
So all Highlights are working as expected, both in the present diplodealview and in the IDS mod.

**Comment by ricanuck** [comment]
As there was no further feedback on the issue, and we have tested the alleged save file to demonstrate the feature is working as intended, I am closing this item.

**Comment by JHCD** [comment]
That was not as intended, I don't want to see highlighted ressources from deals between other civs.

I will check this after the new implementation.

**Comment by ricanuck** [comment]
Hmmm... I see your point. The thing is, a good player (notice I am not even saying master player) will be able to know exactly that (that the other civ is receiving a resource from a third unknown civ) by just asking "What will you give me for this?" and analyzing the AI valuation of the item. If the valuation is low when it is expected, given the relations between trading parties, that is should be higher, the good player already knows. Therefore, it can be strongly argued that the information is really there, but in an indirect manner.

**Comment by ricanuck** [comment]
@JHCD : definition of software bug:
1. A software bug is a problem causing a program to crash or produce invalid output. The problem is caused by insufficient or erroneous logic. A bug can be an error, mistake, defect or fault, which may cause failure or deviation from expected results. Source: https://www.techopedia.com/definition/24864/software-bug-
2. A problem that causes a program to produce invalid output or to crash (lock up). The problem is either insufficient logic or erroneous logic. For example, a program can crash if there are not enough validity checks performed on the input or on the calculations themselves, and the computer attempts to divide by zero. Bad instruction logic misdirects the computer to a place in the program where an instruction does not exist, and it crashes. Source: http://www.pcmag.com/encyclopedia/term/51664/software-bug

This is not a bug. The code is doing exactly what it is supposed to, and is not showing inconsistent results. The fact that you don't want the result is not a bug, but a feature issue. We can debate if we should or should not show some info, but that does not make a bug.

I will not enter a childish bug-notabug contest with you. Let the owner decide.

@chaorace : please resolve this at your discretion.

(this is what happens when you go from Dictatorship to Democracy in one sudden step) ;)

**Comment by chaorace** [comment]
Yes, I was rather enjoying the enlightened autocrat thing, alas, you two bring too much to the table to pass up!

Right, so it's not bug. The goal of the highlighting is to alert you when the player already has a resource you could be trading him. The goal _isn't_ for it to just be a visual shorthand for what's visible on the other side of the deal tray. That being said, there is still an issue here, as clearly demonstrated by the _appearance_ of what _feels_ like a bug.

Okay, so summing it up: it's not a bug in the software, it's a bug in the users. We need to accommodate for the incorrect assumption users are going to make by preemptively and transparently informing them what that highlighting is supposed to mean. I feel the best way to achieve this is by having a highlighted item's tooltip say "TRADE PARTNER ALREADY HAS A COPY OF THIS X". We don't divulge how, or why, because that is potentially very unfair information, but we do at least divulge _how_ what we're telling them already works

**Comment by chaorace** [comment]
That being said, I'm re-christening this issue as an enhancement in light of it's non-bug nature, instead suggesting that we need to be more clear about exactly what this highlighting means.

**Comment by ricanuck** [comment]
Agreed. OTOH, I will not touch this until we test, and then decide, about IDS addon. You know my bet where my bet already is; we can modify that addon a piacere, when/after we decide what we want from it, but the overall design and presentation is excellent and we should use that.
Any chance you commit that one so everyone interested can also test it? I am using it full time now, no regrets.

**Comment by JHCD** [comment]
Call it like you want, but sorry, removing cheating isn't an enhancement...
Something I could know isn't the same as directly shown without thinking.

It isn't allowed to take a opening book to a chess tournament. 
They are all well known, but have it in mind or lose it.

**Comment by JHCD** [comment]
Same cheating issue with the new mod.
You haven't access to this information normally...

![trace_screen_spain](https://cloud.githubusercontent.com/assets/12496340/24291991/9821a472-108b-11e7-91ae-e35ce88ff285.jpg)

**Comment by ricanuck** [comment]
@JHCD : not directly, no. It's relatively easy to filter out, same with the city info. I was about to do this before integrating the mod, but decided to leave them in to hear more feedback.

For the resources that the other civ already posseses, and that come from another civ, should we:
1. Leave as is (assumes the indirect way of "knowing", low trading valuation, is not cheating)
2. Adopt chao's solution: mark them as "already possesed by this civ" (almost no difference with 1)
3. Take them out and leave only the ones that come from "suzerained" CS (direct info available)

For city info of trading partner, should we:
1. Leave as is
2. Take out all yield info
3. Take out some yield info

**Comment by JHCD** [comment]
I prefer only to show known and not to declose hidden informations.
So I would select 3 and 2 :)

**Comment by emperorfool** [comment]
My goal with BUG Mod for Civ4 was to give the player all the information they can find in the vanilla UI, but quicker. If you can trivially deduce that an AI is receiving a resource from another player—even if it's not explicitly shown in the UI—I'd show it. It's a bit of a gray area I agree, but I think much less murky than the chess metaphor.

I'd liken it to watching a chess match where you aren't told who is playing white, and your job is to guess. But you get to see the list of moves the players took during the game, Bob moved first, and you know that white always moves first. Well duh, Bob is playing white. That's not a fun game to play, so just tell the player. :)

**Comment by ricanuck** [comment]
I decided to remove the "Trade with other civ" imported resources. Vanilla civ 6 does not give any indirect way to know if a resource is being imported by a given civ from a third party civ. Gossip items, at best, only say "Civ A is trading with Civ B", but that is not enough to deduce that some specific resources is being traded, even if the map is known. Valuation of items by the AI has also proven to NOT be trustworthy as a way to deduce that the civ already has some resource (this is not Vox Populi's AI, it's Firaxis AI).

Thus, non-cheat policy in this case means no showing of imported resources when the local player is neither the importer nor the exporter.

**Comment by JHCD** [comment]
There is an issue with this ressources:

IDS Terry before trade:
![error_ids_ressources](https://cloud.githubusercontent.com/assets/12496340/24723949/accdbf56-1a49-11e7-8fa8-2df97b3362ff.jpg)

Trade:
![urs_trades](https://cloud.githubusercontent.com/assets/12496340/24724823/d65e34b0-1a4c-11e7-916b-a425f5dfa0b8.jpg)

IDS after this trade:
![error_ids_ressources2](https://cloud.githubusercontent.com/assets/12496340/24724443/63c28f10-1a4b-11e7-805d-8738678db0ee.jpg)

Report-Screen:
![urs_ressources](https://cloud.githubusercontent.com/assets/12496340/24724223/a4cca6ea-1a4a-11e7-94f6-7c44e5b92df9.jpg)

All screenshots are from the same game round.
I have no other merchandise trade.

There are some things cracy...
- Duplicate or not?
- Where is my Whale and Salt?
- I'm not sure Terry has Oil.
- ...

**Comment by ricanuck** [comment]
Jens, I never saw what you report in my games, I just finished a long game and the diplo deal screen was always accurate... I don't know what happened in yours, but if we cannot replicate or test, we cannot leave this open.

**Comment by JHCD** [comment]
Here is my savegame to the pictures above:
[MONTEZUMA 1 - IDS dr.zip](https://github.com/CQUI-Org/cqui/files/902541/MONTEZUMA.1.-.IDS.dr.zip)

**Comment by ricanuck** [comment]
You are right, something is effed up in that game with IDS... I will have to investigate more, I don't see the wrong in the code yet, but there are definitively discrepancies between IDS and vanilla diplo deal view in your save in terms of results. Vanilla shows Terry having Oil, although I couldn't find it either... perhaps hiding underneath some district or wonder... this game is so badly coded in terms of UI, geez...
I will try and dig into this later.

**Comment by JHCD** [comment]
Oh, one idea for the _oil_ could be the Great Person...

**Comment by ricanuck** [comment]
ah, exactly! still, there is something wonky with IDS here and I cannot find the problem yet...

**Comment by ricanuck** [comment]
aorite, I think I got it. Very silly bug from original IDS. Try the file with your saves and let me know if it works fine now. It is working fine in my setup with your file, but you know that game better and will find any discrepancy faster, if any.

https://drive.google.com/open?id=0B_TA2f5G0Z78cWN5bUdZUnQwUk0

**Comment by JHCD** [comment]
Let's start the next iteration ;)

The Bonus ressources from "Sansibar" aren't shown in the IDS screen:
![20170409154805_1](https://cloud.githubusercontent.com/assets/12496340/24837823/af0cd52c-1d3c-11e7-9552-4277919dae96.jpg)

![20170409154756_1](https://cloud.githubusercontent.com/assets/12496340/24837818/8a8f0f1c-1d3c-11e7-9d2f-4600e0bd82f9.jpg)

![20170409154741_1](https://cloud.githubusercontent.com/assets/12496340/24837813/6976b320-1d3c-11e7-8bc5-ae9a89bdd802.jpg)

The other ressources seems to be correct.

Here is the savegame:
[FRIEDRICH BARBAROSSA 2 - IDS dr.zip](https://github.com/CQUI-Org/cqui/files/908217/FRIEDRICH.BARBAROSSA.2.-.IDS.dr.zip)

**Comment by ricanuck** [comment]
@JHCD @chaorace : the last one is NOT a bug. Sanzibar is a special case of 2 lux bonus resources that they "have" in their coffers for their suzerain, and not as part of the map. Those 2 resources are truly UNIQUE and unrepeatable, therefore will NEVER be trade-able. Thus, by definition, they do NOT belong in the diplo deal view. Remember that in vanilla only trade-able items are shown, regardless of replication, but non-tradeable are never shown.
The function of IDS is to show trade-able resources, and the ones that are duplicate to help the player NOT to repeat trades. The function of IDS is NOT to show ALL available resources.

NOT a bug.
I will not close this issue (although I should), and will let Chris decide if to close it or not.

**Comment by JHCD** [comment]
If it's not accessible in the API, it's okay for me.
