### ISSUE TITLE
Show strength modifiers as tooltip in unit panel

### ISSUE THREAD

**Issue by plucko00** [CQUI-Org/cqui#417]
Giant's Causeway provides "Land combat units that enter adjacent Tiles receive the ability 'Spear of Fionn' (+5 Combat Strength). " but there's no way as far as I can tell to know which units that's been applied to, and it's difficult to keep track of which units have been adjacent to it.  Can it be at least shown as one of the units promotions?

**Comment by chaorace** [comment]
I don't know how the game handles this effect, but, if it's not just a regular promotion effect that gets ignored by the UI, I just don't think it's worth the code complexity

**Comment by SpaceOgre** [comment]
I'm not sure how the game stores the information, but you see it when you hover over an enemy unit/city like admiral bonus and the like. 

It would be great to be able to see all these bonuses without having to hover over an enemy.

**Comment by chaorace** [comment]
@SpaceOgre That seems like a more sensible suggestion that still solves the root problem at hand here. Any suggestions towards the best way to approach this?

**Comment by SpaceOgre** [comment]
Something like this might work:
![image](https://cloud.githubusercontent.com/assets/381657/24321659/007abf4c-1152-11e7-97cc-a86315629e3f.png)

Since I'm not completely sure what else is show in this layout I think the least invasive way is to just show a summation of the all the extra bonus damage and then add a new tool-tip (or add it to the current one) that shows the break down.

**Comment by chaorace** [comment]
Okay, that seems like a strong contender for a good way to represent the info, changing the issue title to reflect this

**Comment by SpaceOgre** [comment]
Looked more into this today and the extra information is collected from CombatManager and I can't figure out how to use it without a "target". Tried using the selected unit as target as well but only get nil back.

And it seems like CombatManager is protected since I can't access it from the FireTuner. Does anyone have an idea how I could move forward?

**Comment by JHCD** [comment]
> One thing to try might be to always do this: UnitManager.GetUnit(1, 0) since we always are player 0 in single player it could work but it is not pretty.

If you hard-coded player 0, than _Hot Seat_ wouldn't work.
Is there no playerID available?

**Comment by SpaceOgre** [comment]
In this case playerid is the first number in GetUnit, the second ins the unitid for that player. I guess it could be possible to get a list of players and the loop through until you find a combat unit, then store it to not have to do it all the time.

Is there a way to find out what methods a Unit object/table have? In civ 5 there is methods to get the modifiers straight from the unit.

**Comment by JHCD** [comment]
The methods are mostly similar to Civ 5.
For Civ 5 you could take a look here: http://modiki.civfanatics.com

I don't know a newer list.

**Comment by SpaceOgre** [comment]
Yeah, I looked at that list to but no luck since it seems most of the names are changed for civ 6. Did try some of them and did some guesses to what they could be called now but no luck.

**Comment by SpaceOgre** [comment]
You can use this to get all the available functions for an object:
`for key,value in pairs(getmetatable(UnitManager.GetUnit(0,2))) do for key2,value2 in pairs(value) do print(key2, value2); end end `

Replace `UnitManager.GetUnit(0,2)` with your desired object. Sadly it does not seem to exist a method to get modifiers on the unit. Since this is only usable for Spear of Fionn and General/Admiral the solution might be to big/hacky for such a small benefit.

**Comment by ricanuck** [comment]
Not sure it will work. Many of the modifiers are strictly relative to the enemy unit, so it would be impossible to represent in the unit panel as the targets are dynamic. If we only show the static modifiers, then people will start to complain that not ALL modifiers are shown and therefore "this mod sucks dude"...

Lose-lose if you ask me. Better to not innovate here.

**Comment by chaorace** [comment]
Fair enough, I suppose I'll be closing this issue then
