### ISSUE TITLE
Occasionally cities won't appear as an option to "Cede" in diplo menu

### ISSUE THREAD

**Issue by gelodgreat** [CQUI-Org/cqui#439]
No Cede in Diplomacy in some leaders
![bug](https://cloud.githubusercontent.com/assets/20021423/24405830/d5644220-13f8-11e7-809f-9ba7e33f64f0.png)

**Comment by chaorace** [comment]
Forgive my ignorance if I'm missing something obvious here. By "cede", you mean give up cities, right? If that's the case, there's a full list of cities for you to choose from right on the list.

**Comment by gelodgreat** [comment]
If you look in Xi'an i captured it from the chinese but we can have peace and they can cede their cities to me. I don't see it like this below.
![like](https://cloud.githubusercontent.com/assets/20021423/24406704/5dd85a18-13fb-11e7-838d-128d936f8a75.png)

**Comment by chaorace** [comment]
Okay, thanks for elaborating! Could you provide an affected save file?

**Comment by gelodgreat** [comment]
https://drive.google.com/open?id=0B0k2qUZxX80KMmJBN0lpTHVkcTg

**Comment by ricanuck** [comment]
something is odd... code clearly makes occupied cities be listed first on both sides... it's not happening in your case. Patch is downloading in my Steam, I wonder if I will be able to test this, or if new patch will break everything (expected)...

**Comment by ricanuck** [comment]
OK, checked your save (not loaded) and you have 1,274,589 mods enabled besides CQUI. MY strong bet is that you have a mod conflict somewhere in that long list. RED modpack perhaps?

**Comment by gelodgreat** [comment]
This is my list of mods

Better Espionage Screen
DeityPlusPlus
Even_MOAR_Units_Aztec
Even_MOAR_Units_Poland
GDG Additional Airslots in Aircraft Carrier
GDG Assorted Mod
GDG Build GreatWall Outside
GDG Lower War Weariness, Raze Penalty, Warmongering Penalty
GDG No Penalty Different Governments
GDG Scout_Submarines_Ranger Ignore Borders
GDG Settlers makes road after settling
GDG [Personal] The Chosen Unique
JFD's de Gaulle of France
JFD's Frederick II of Germany
JFD's Louis XIV of France
JFD's Nicholas II of Russia
list.txt
MOAR_Units
R.E.D Even MOAR Units Aztec
R.E.D Even MOAR Units Poland
R.E.D JFD's de Gaulle of France
R.E.D JFD's Frederick II of Germany
R.E.D JFD's Louis XIV of France
R.E.D. for MOAR Units
R.E.D. for Poland DLC
R.E.D. Modpack
R.E.D. Modpack for Australian DLC
Real Era Stop
Show Diplomatic Deals
Tomatekhs Historical Religions
Unit Report Screen
Yet (not) Another Maps Pack
YnAMP - Cliff of Dovers Yield Tweak
YnAMP - Faster Movements
YnAMP - More CS for Europe
YnAMP - More CS for the World
YnAMP - More Distance Between Civilizations
YnAMP - Remove Close CS
YnAMP - Resources Placement Tweak

**Comment by tones** [comment]
I'm seeing the same bug — in the "Make Peace" trade dialogue, some city names are listed twice, and there is no option to cede captured and occupied cities.

I'm only running one other mod ([RED](https://github.com/Gedemon/Civ6-RED-Modpack.git))

**Comment by tones** [comment]
Screencap with cqui running 
![screen shot 2017-03-28 at 2 35 23 pm](https://cloud.githubusercontent.com/assets/289020/24428661/fd044184-13c3-11e7-8a12-f5001e73f633.png)

**Comment by emperorfool** [comment]
FWIW I'm running only CQUI and the DLC, and in my game yesterday I could not negotiate the peace deal with England at all. I could open the panel and click Reject or Accept, but I couldn't see what was being offered nor make any changes. Nothing was listed on either side (money, resources or cities) anywhere.

During a later war with another player, I was able to use the new screen just fine. It's very nice when it works! I'll see if I can dig up a save.

**Comment by ricanuck** [comment]
@emperorfool , hello old BUG friend! Long time no see! Good old times... here we trying to BUGinize Six now... care to join us?
Save is good, only CQUI enabled, so we can test what is going on... likely the patch.

**Comment by tones** [comment]
Here's the save game for the screen above 

[PHILIP II 193 1320 AD.Civ6Save.zip](https://github.com/CQUI-Org/cqui/files/877195/PHILIP.II.193.1320.AD.Civ6Save.zip)

**Comment by ricanuck** [comment]
@tones, given that I suspect RED for that case, can you make sure RED does not overwrite the same file (diplomacydealview.lua)?

**Comment by gelodgreat** [comment]
RED only overrides Units.artdef

**Comment by tones** [comment]
...yup @gelodgreat is right

**Comment by ricanuck** [comment]
Confirmed bug with the original IDS mod code. The occupied cities are still there, in the case of tones, India peace deal, the first two cities are Angra and Delhi, although the text on top of the buttons does not correspond to them. If you ask for those two in the peace deal, India will accept and you will take control of Angra an Delhi.
Something changed in the Firaxis functions so that the names are not correct for the occupied cities. Ironically, on the other side, names are correct.
Need to find the culprit. This is one of those "ball br&%*ers"...

**Comment by ricanuck** [comment]
OK, after wasting a lot of time trying to solve this, it ends up being (surprise!!!) a bug in vanilla (new patch). You can see it happening in vanilla, only that the UI fools you with naming the city button as XYZ-cede, but if you hover over the button and read the tooltip, you will see that everything corresponds to another city (those cities that you see "duplicated" in IDS).
Once again, Firaxis effed up, no surprise there... I am not sure how to compensate for this, the IDS code is working as intended, as it was before the patch, but now GARBAGE IN GARBAGE OUT.

Go to Helheim, Firaxis.

**Comment by gelodgreat** [comment]
But it occured to me before the update. How's that? Can it be fixed?

**Comment by ricanuck** [comment]
really??? Never seen it before... maybe the bug is older... but it is a vanilla bug, that's for sure, easy to reproduce if you look beyond the button text (tooltip is an accurate representation of which city the button is really linked to).

**Comment by gelodgreat** [comment]
yes. thanks. btw is it possible to disable diplomacyview and have vanilla?

**Comment by ricanuck** [comment]
yes, quick solution for you would be to go into the IDS folder inside Integrations, and just delete or rename both diplomacydealview files (lua and xml).

**Comment by ricanuck** [comment]
@chaorace @JHCD : this is a SERIOUS Firaxis bug. To reproduce, load tones above save or any other save you may have where you have occupied cities in a war and peace has yet to be made. Load that save without any mod (forceload through Firetuner). If you use tones save above, the mix-and-match Hindi cities are: Angra-->Calcutta, Delhi --> Patna.
Now open a peace deal with India, and select Cede Angra and Cede Delhi. Ghandi will accept, but now try to select Calcutta and/or Patna to add to the deal, and you will not be able to, EVEN IF GHANDI IS WILLING TO ACCEPT ALSO THOSE TWO (I tested). The internal value types of the cities are mismatched together, and that is why you cannot select Calcutta and Patna after selecting Angra and Delhi, because THEIR INTERNALS ARE THE SAME!!!!!

Idiots.

With that said, I managed to fool/overcompensate the faulty functions with other checks, and made it work as expected. Will upload the modified code as another branch so you can test it. It is a very convoluted solution, that seems to work fine and "pseudo-solve" Firaxis stupidity, but will have to be "counter-convoluted" IF/WHEN Firidiots correct this huge issue.

Idiots.

**Comment by ricanuck** [comment]
Applied censorship to the last messages so that you can refer to it as a bug report for Firaxis.

**Comment by chaorace** [comment]
@ricanuck I tried reporting the last bug we encountered, but all I got back was an email requesting that I record the bug in progress... _record an API bug_. When I mentioned that the request didn't make any sense in the context of the issue, I received no reply for 7 days before my ticket was closed silently

**Comment by ricanuck** [comment]
yeah... 2K. 2K = KK. In Spanish, a double K you would call it like this:

KaKa. And you know what KaKa means in Spanish slang.

You can always report it on Redit and CivFanazis... Firaxis people seem to highly prefer Redit, so you can use that first. Don’t forget to mention yours truly (I can’t post on CivFanazis because I left for good, and have no Redit account).

cheers,

**Comment by chaorace** [comment]
@ricanuck If we're posting bugs to Reddit, I'd rather aggregate several first and then post it. I get the feeling just one bug, albeit major, risks not getting much upvote traction. Plus, I get the feeling going to Reddit about a bug is a bit of a magic-bullet that wouldn't work more than once or twice. We might as well make a list of lots of bugs so people are more inclined to feel like it's worth the attention _and_ so that when it does get high up, we'll get more mileage out of it.

I'm going to start keeping track of these base-game issues [here](https://github.com/chaorace/Civ6-UIFiles/issues?q=is%3Aopen+is%3Aissue) so we can keep better track

**Comment by ricanuck** [comment]
OK. Then we shall use my convoluted code and be the only ones to have a correctly functioning diplo deal screen. :)

**Comment by ricanuck** [comment]
Hahahahahahaaa!!!!

https://forums.civfanatics.com/threads/unable-to-ask-for-occupied-city-to-be-ceded-1-0-0-129-260180.613212/

I can make my educated guess: Harald has only two cities. the capital and the occupied city. Both have the same underlying ID values, so the DealManager genius hides both from the deal window, and therefore there is nothing to cede in peace deal, although there clearly is a second city that is occupied.

Yeah...

**Comment by ricanuck** [comment]
It also begs the question to @gelodgreat : are you sure it happened to you before the patch? Because it starts to smell like it was introduced by the patch... maybe you triggered it after the patch with a save you started after?
Also, there are some reports that show that the new Cyrus is never seeing the option to Cede cities because of his trait (he doesn't need them ceded to benefit from them). Either WAD or another bug, I sense that they may be related. They may have changed the code for DealManager to accomodate Cyrus, and created this mess.
NO surprise there. Firaxis post-civ4 at its best...

**Comment by chaorace** [comment]
[Patch went up just after 11PM on the 28th](http://i.imgur.com/UKKmCxz.png)

[This issue went up 8AM on the 28th](http://i.imgur.com/nQziPYq.png)

Unless gelodgreat is actually a Firaxis dev in disguise leaking API bugs from private builds, I think it's safe to say that this was a pre Spring 2017 issue. Side-note: Reddit doesn't properly acknowledge the EST/EDT distinction in its timestamp strings

**Comment by ricanuck** [comment]
One way or the other, it's a huge issue that, as I told you, is game breaking, as is starting to get proven by the surfacing reports. And so far, the only attempt I know of to fix it is right here, and so far, it has worked for me,

**Comment by chaorace** [comment]
I don't disagree, I plan to merge your PR tonight

**Comment by ricanuck** [comment]
That save in CivFanazis is useless, he uploaded a save from after the war was ended... plus, some reports suggest that Cyrus does not see the Cede option because of his UA.

**Comment by ricanuck** [comment]
did you test the code also?

**Comment by chaorace** [comment]
@ricanuck I've set aside an hour tonight to play with your feature branch loaded

**Comment by ricanuck** [comment]
Somebody should answer to this guy... say Hello from Aristos to the Civfanazis guys... :)

https://forums.civfanatics.com/threads/unable-to-ask-for-occupied-city-to-be-ceded-1-0-0-129-260180.613212/#post-14710807
