### ISSUE TITLE
IDS: Changes on Ressource-Icons

### ISSUE THREAD

**Issue by JHCD** [CQUI-Org/cqui#478]
I used the new IDS some games, very nice! Thanks for integration.

But I have some wishes. ;)

![ids_colors](https://cloud.githubusercontent.com/assets/12496340/24626941/4c6ed236-18b3-11e7-8e5d-fbca3727411d.jpg)
 
1.) It is possible to fit all icons to the same size.
2.) Could we change the using of the colour?
Black ones are okay, but I focus on the grey one every time I open the screen...
Cascade should be: black: suz, blue: duplicate, grey: non-existent

**Comment by ricanuck** [comment]
Size difference is because the buttons for black are disabled.
Colors is a matter of preference, so until there is some kind of consensus about that, I wouldn't change them. Especially Blue, as that is the vanilla color for TRADE-ABLE.
We could make the blue a lighter blue, to make it more contrasted in regards to the background (that is why Grey attracts your attention now, it has more contrast).

**Comment by JHCD** [comment]
Okay, you have the point... let us still use TRADE-ABLE.
Is it possible to make NON-trade-able a litte bit inconspicuously?

**Comment by ricanuck** [comment]
Not sure I understood your last... NON-tradeable = Black now...

**Comment by ricanuck** [comment]
1 is done, buttons are now all the same size.

**Comment by JHCD** [comment]
@ricanuck 
> Not sure I understood your last... NON-tradeable = Black now...

That was an idea, yes... or darker grey or whatever... so that you will focus on the right ones...

**Comment by chaorace** [comment]
Closing issue tentatively. Is everyone satisfied with the current state of IDS?
