### ISSUE TITLE
Latest patch has broken the civic/tech/policy panels

### ISSUE THREAD

**Issue by islandboy** [CQUI-Org/cqui#500]
The latest path (4/14/17) has broken the functionality of the civic, tech, and policy panels. Clicking on any of those icons does nothing. You can click any of the options down the left-side panel, but actually viewing the trees is not possible.

In addition, the turn is reset to "1" and the date to 2100AD.

Any game that has this mod enabled is unplayable, including new games. New games can be created and played if the mod is disabled however.

**Comment by ProustIdee** [comment]
Are you using the CQUI from the Steam workshop?

If not, make sure you are using the newest version:
https://github.com/CQUI-Org/cqui/archive/master.zip

**Comment by islandboy** [comment]
Oh, sorry forgot to give some details.

Yes, I'm using it from the Steam Workshop and I'm running steam-os (linux), however this appears to be affecting all os versions as judging from the comments.

It is the newest version that's causing the problem.

**Comment by SpaceOgre** [comment]
Could you download and test the latest nightly from the link ProustIdee posted and test if the problem persists? I'm not seeing this problem on my end with the latest nightly, so it might be a problem with the steam version.

**Comment by islandboy** [comment]
I downloaded and diff'd the directories and there the same. Are you sure that link points to the nightlys?

**Comment by islandboy** [comment]
It's possible this could be a mac and linux issue only, but not confirmed.

**Comment by ricanuck** [comment]
I cannot replicate. Win7 Pro 64 here.

**Comment by davidmckenzie** [comment]
Seeing this issue on Mac, but not on my Windows box.

**Comment by SpaceOgre** [comment]
What version is the game on Mac/Linux? Have they received the spring patch? If not I think that might be the problem.

**Comment by cjcjameson** [comment]
Fix for me was:

```
cd ~/Library/Application\ Support/Steam/steamapps/workshop/content/289070/870911250
git checkout d97bb439ce732e5303d1451cd3559a2063c9939f
```

Because the spring patch probably broke macOS

**Comment by jyrmar** [comment]
@SpaceOgre Mac/Linux haven't received the spring patch yet.

@cjcjameson any other steps?  Per another site, I did the following after the 'git checkout' command...

git checkout -b revert.spring

... no luck.  When I load a saved game, the Science/Culture/Govt issues still exist.

**Comment by cjcjameson** [comment]
Yep so:

- `git checkout -b foobar` doesn't change the code in the file tree, but it does label the version of the code which you've "checkout"ed to, for easy navigation.
- Saved games get locked into using CQUI -- you can't reopen them with no CQUI
- However, I don't know the details of whether rolling back to a previous commit should or shouldn't work... there might be come weird details there.
- I'm almost certain that if start a new game at `d97bb439ce732e5303d1451cd3559a2063c9939f`, and then a fix comes out, you'll be able to continue it.

Note that in my workflow, I had been mucking around with the underlying directories a lot before coming across the minimal fix above. So I ended up nuking my install almost completely to make sure I had a fresh start (steps below). However, I don't think that should be necessary for most people...

```
# uninstall from Steam UI
cd ~
rm -rf Library/Application\ Support/Steam/steamapps/common/Sid\ Meier\'s\ Civilization\ VI
rm -rf Library/Application\ Support/Sid\ Meier\'s\ Civilization\ VI/
rm -rf Library/Application\ Support/Steam/steamapps/workshop/content/289070
```

**Comment by cjcjameson** [comment]
Confirmed: I've narrowed the macOS bug to the Spring patch commit and/or one other commit (which merge-conflicts without the spring patch commit, so I didn't test it independently)

d97bb439ce732e5303d1451cd3559a2063c9939f
8018286b1fa91fcb97127e5b87c4ff6ac6c0df34

If you want to use the latest release with only those two commits removed, instead of the instructions above:

```
cd ~/Library/Application\ Support/Steam/steamapps/workshop/content/289070/870911250
git remote add cjcjameson https://github.com/cjcjameson/cqui.git
git checkout cjcjameson/cjcjameson_diagnosis
```

**Comment by SpaceOgre** [comment]
It is most likely 8018286b1fa91fcb97127e5b87c4ff6ac6c0df34 that is the culprit since all the new files in that commit is from the spring patch.

**Comment by chaorace** [comment]
Looks like the issue is may be related to the naming of the new WorldTracker.lua import, which should be lowercased. Any non-lowercased files break Linux pretty much unconditionally. Yep, that's a thing that happens, so we can fix that relatively easily.

This issue shouldn't affect OSX if my theory is correct, since that OS is case-agnostic

**Comment by chaorace** [comment]
@cjcjameson Are you testing on OSX or Linux?

**Comment by islandboy** [comment]
I just wanted to confirm that cjcjameson suggestion above **worked**: I loaded my game and was able to open the panels.

By the way, I had to do a git fetch. So here's what I did to be complete:

git remote add cjcjameson https://github.com/cjcjameson/cqui.git
git fetch cjcjameson
git checkout cjcjameson/cjcjameson_diagnosis

I'm on linux by the way, and the path for linux is:
Steam/SteamApps/workshop/content/289070/870911250

**Comment by chaorace** [comment]
@islandboy Try renaming WorldTracker.lua to worldtracker.lua. Tell me if that fixes the issue for you

**Comment by islandboy** [comment]
@chaorace Can you explain this:

"_Any non-lowercased files break Linux pretty much unconditionally_"

Ok, I can test that. Do you want me to undo @cjcjameson changes?

**Comment by islandboy** [comment]
@chaorace Wait, I don't think the lower case is the issue because with @cjcjameson patches that file is still camel-humping: "WorldTracker.lua". And the game seems to be working.

**Comment by chaorace** [comment]
@islandboy Yes, just try the change with the base nightly

Linux is a case-sensitive kernel. That means a file named WorldTracker.lua and a file named worldtracker.lua are _not_ equivalent in Linux-based environments. This is not the case in OSX or Windows, which ignore case and would consider these two files equivalent.

It would seem that, on Linux by some process, the internal file-tree is still case sensitive, yet considers all files in the environment lowercased, unless imported via mod, in which case the case of the filename is preserved. This means mods can very easily break Linux games unless they take care to lowercase _all_ file names

Also, WorldInput.lua didn't exist before the commit in question, which probably explains why it doesn't affect anything despite looking the same (since it's no longer included in the file manifest)

**Comment by chaorace** [comment]
@islandboy While I've got you, could you also provide [a gist](https://gist.github.com/) of the the contents of lua.log, which is found under the same general location as your save files (directory structure would look like "Sid Meier's Civilization 6/logs")

**Comment by islandboy** [comment]
@chaorace I'll let me give that a shot

Ok, this is a true statement:

> Linux is a case-sensitive kernel. That means a file named WorldTracker.lua and a file named worldtracker.lua are not equivalent in Linux-based environments.

But you lose me here:

> It would seem that, on Linux by some process, the internal file-tree is still case sensitive, yet considers all files in the environment lowercased...

Linux is always consistent: Those two files will always be different in linux.

**Comment by islandboy** [comment]
@chaorace Renaming that file didn't work.

By the way, I couldn't find a lua.log file in the steam directory structure. Maybe it's called a different name is linux. Is there a string I can grep for?

**Comment by chaorace** [comment]
The internal file tree I'm referring to is the one used in the Civ 6 engine. The filetree is flat, unlike what we see in modern operating systems. This means _all_ files, from mods and base game, are stitched together into a single working directory without subfolders. This process is probably employed so that we're free to organize the files as we see fit, independent of how they may be arranged in the base game. The issue is that the original case of the base-game files is not preserved when creating this flat working directory. They're all treated as lowercase! This is an issue because apparently this lowercasing process is skipped when importing mod files to the same working directory. Allow me to demonstrate with a flow-chart and example:

We start with a complex tree like this:
Base - Dir1 - File2
                  - File3
        - Dir2 - File4
        - File1

All lua/xml files are taken from the game directory and stitched into a working, flat directory, the tree now looks like this:
Base - File1
        - File2
        - File3
        - File4

The files are now all converted to lowercase:
Base - file1
        - file2
        - file3
        - file4

Mod files are now written into the working directory, replacing any files with a matching name. On Windows/OSX, with files named "File1", "file2", and "New1"  that process looks like this:
Base - file1 <- File1 overwrites
        - file2 <- file2 overwrites
        - file3 --No match
        - file4 --No match
       - New1 --New file created

However, on Linux-based OSes, that process breaks down because the lowercasing step doesn't happen first, it looks like this instead:
Base - file1 --No match
        - File1 <- New file created
        - file2 <- file2 overwrites
        - file3 --No Match
        - file4 --No Match
        - New1 <- New file created

Finally, the mod files are renamed to lowercase:
Base - file1 --No match
        - ~~File1~~ <- Can't lowercase, file discarded
        - file2 <- file2 overwrites
        - file3 --No Match
        - file4 --No Match
        - new1 <- Renamed to lowercase

The lua.log file is not in the workshop directory, it's in the same directory where your _saves_ are stored

**Comment by islandboy** [comment]
I searched the entire steam directory structure and I have no lua.log file. It might be a different name in linux... I'm guessing. And I have no idea where the saves are stored. Let me see if I can find it...

**Comment by chaorace** [comment]
Anyways, it looks like this issue affects OSX as well based on feedback from the comments, so it's not an issue specifically with the lowercasing thing. That means it's probably an issue with an engine difference between Spring/Summer patches. I'm setting up a SteamOS install on my Hyper-V server now and will be harvesting error logs myself when that finishes. Though, my only ISP option is hot garbage and I'm pulling about  1 mb/s right now, so the necessary downloads could take a few hours. If anyone could send lua.log pastes in the meantime, that may considerably expedite the process

**Comment by islandboy** [comment]
Ok thanks!

I'm trying to look for the saves directory but the directory structure is a mess in linux...

What's in the lua.log file? Maybe I can do a string search.

**Comment by chaorace** [comment]
It's going to definitely be called "Lua.log", probably in your "My Games" folder or a similar folder in your user home directory.

**Comment by islandboy** [comment]
Holy crap! Found it!

ok, so on linux the games are saved here for civ6:
`~/.local/share/aspyr-media/Sid\ Meier\'s\ Civilization\ VI/Saves`

And I found the Lua.log. Let me send that to you.
By the way, the Lua.log can be found here:
`~/.local/share/aspyr-media/Sid\ Meier\'s\ Civilization\ VI/Logs/Lua.log`

**Comment by islandboy** [comment]
Here's the gist: <script src="https://gist.github.com/islandboy/8b14404f78e41c372ae82817113f8e52.js"></script>

**Comment by islandboy** [comment]
Let me know if you have any issues reading the file.

I'm also attaching the file here as well:
[Lua.log.gz](https://github.com/CQUI-Org/cqui/files/924516/Lua.log.gz)

**Comment by chaorace** [comment]
FTFY: https://gist.github.com/islandboy/8b14404f78e41c372ae82817113f8e52

**Comment by SpaceOgre** [comment]
The casing of WorldTracker.lua was not changed in that commit, atleast not what I can see. It was camel cased when I started working on that specific feature. But it should be changed to avoid problems in the future.

**Comment by chaorace** [comment]
@SpaceOgre [I agree](https://github.com/CQUI-Org/cqui/issues/500#issuecomment-294369305) and also, [yes](https://github.com/CQUI-Org/cqui/commit/a97ea5fcd9c8d2961a2835fdaa0b9e46e009e5bd)

Now that we've captured a stack trace of the given issue, I'm reverting the workshop release to the last weekly until we can address this issue

**Comment by chaorace** [comment]
Just to keep you guys updated, I'm pursuing a solution using azure, which is probably going to be the most cost effective solution for me running a linux test environment (I can't run an environment like this on my machine natively because of a very hacky custom driver I use with nonstandard hardware). I've hit a minor snag however with my azure account getting flagged so I'm waiting on support to clear me before I can patch this

**Comment by davidmckenzie** [comment]
The Mac/Linux update was supposed to be out mid April, so could drop any day now. Not sure if you'd wanna spend the time debugging when it could resolve itself soon enough anyway :)

https://support.aspyr.com/hc/en-us/articles/216979606-Civilization-VI-STEAM-KB

**Comment by chaorace** [comment]
It's mostly an issue of keeping the weekly current with the nightly without fragmenting the workshop userbase, I wouldn't be too upset if they dropped it soon though

**Comment by islandboy** [comment]
@chaorace I can test the linux stuff if you want. The only caveat is that my schedule is unpredictable. But I'll do my best. I some time in the evenings when I get home from work. The weekends I have a bit more time.

**Comment by tgrav21** [comment]
Version 1.0.4 was just released for Mac. As soon as I download the update (my version is through Apple Store) I will try out the mod and see if the issue remains.

**Comment by chaorace** [comment]
Welp, I guess this issue resolved itself then. Yay?
