### ISSUE TITLE
Add bind for doubleclick in productionpanel: select production AND close cityview

### ISSUE THREAD

**Issue by dubert** [CQUI-Org/cqui#81]
When the user clicks the "City needs something to produce" button in the lower right corner
And the map centers on the city and the city view pops up
After selecting an item to produce, the city view does not dismiss automatically (it does this without the mod)

It's annoying because the user has to dismiss out of the city view every time. And this has made me accidentally change what I was building in a city a few times.

**Comment by chaorace** [comment]
The old behavior used to be that the cityview changed every time production was selected, this was changed because it made using the cityview a lot more clunky. I think the best solution to this is adding a bind to something like doubleclick to select production AND close. This way you can trigger the desired behavior from any situation where the cityview would normally be open instead of having a little offshoot of behavior for just one cityview use-case

**Comment by SeanV12** [comment]
I think the default behavior is when you selected production in a city, the next city ready for production would be selected if any, otherwise the production menu would just close. 

I would request an option setting to make this the default, or the option to bind the double click action you describe above to single click, and have double click leave it open as currently implemented.

**Comment by chaorace** [comment]
@SeanV12 What you ask is surprisingly non-trivial. I can attach handlers to clicks and doubleclicks, but not the absence of one. A click event always fires on the first click of a doubleclick event. If I bind close to a single click, it will always fire and close the cityview before the doubleclick event has a chance to attempt cancelling the first event. UI handling is single threaded so I can't just set up actors to handle this issue either. I can't just schedule closing it and conditionally cancel it later when it realizes the doubleclick event isn't coming either, because there is no event for a "not doubleclick". And no, this isn't as simple as setting up a wait loop, because the UI is single threaded and that would cause the game to hang until the wait loop ends.

**Comment by SeanV12** [comment]
Ah ok, I understand the limitation.
Could there be an option in your CQUI Mod Options panel to set the default behavior? Something like an "Auto-close on production" check box?

**Comment by chaorace** [comment]
@SeanV12 Yes, but it's not a priority right now

**Comment by SeanV12** [comment]
Prioritize at your discretion. Thanks for your efforts on this mod

**Comment by TehSeph** [comment]
@chaorace Why not do the inverse? Leave open on a single click and close on a double?

**Comment by chaorace** [comment]
@TehSeph You literally just described the original proposition from two days ago. In fact, It's literally the title of this ticket

**Comment by TehSeph** [comment]
Yeah my bad. I edited my comment almost immediately.

**Comment by chaorace** [comment]
With the introduction of the PQ, this enhancement no longer makes sense, since it would be very trivial to accidentally back out of the menu altogether when spam adding units
